name: Docker publish

on:
  push:
    branches:
      - master
    paths:
      - '8.0/**'

jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker 8.0 image
        run: cd 8.0/cli && docker build -t 8.0 .
      - name: Build Docker 8.0-fpm image
        run: cd 8.0/fpm && docker build -t 8.0-fpm .
      - name: Tags 8.0
        run: |
          docker tag 8.0 ${{ secrets.DOCKER_USER }}/laravel:8.0
      - name: Publish Docker 8.0 image
        run: |
          docker push ${{ secrets.DOCKER_USER }}/laravel:8.0
      - name: Tags latest
        run: |
          docker tag 8.0 ${{ secrets.DOCKER_USER }}/laravel:latest
      - name: Publish Docker latest image
        run: |
          docker push ${{ secrets.DOCKER_USER }}/laravel:latest
      - name: Tags 8.0-fpm
        run: |
          docker tag 8.0-fpm ${{ secrets.DOCKER_USER }}/laravel:8.0-fpm
      - name: Publish Docker 8.0-fpm image
        run: |
          docker push ${{ secrets.DOCKER_USER }}/laravel:8.0-fpm
