name: Docker build

on:
  pull_request:
    branches:
      - master
    paths:
      - '7.2/**'

jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build Docker docker_php72_cli image
        run: cd 7.2/cli && docker build -t docker_php72_cli .
      - name: Build Docker docker_php72_fpm image
        run: cd 7.2/fpm && docker build -t docker_php72_fpm .
